# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "15d289b6a0868199f00cba1dc4d558d2"
name = "product-transfer-umar"
application_url = "https://roses-jane-dip-only.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://roses-jane-dip-only.trycloudflare.com/auth/callback",
  "https://roses-jane-dip-only.trycloudflare.com/auth/shopify/callback"
]
